sentry:
  dsn: '%env(SENTRY_DSN)%'
  # Specify a fixed sample rate
#  traces_sample_rate: 1.0
  # Set a sampling rate for profiling - this is relative to traces_sample_rate
#  profiles_sample_rate: 1.0
  register_error_listener: false # Disables the ErrorListener to avoid duplicated log in sentry
  register_error_handler: false # Disables the ErrorListener, ExceptionListener and FatalErrorListener integrations of the base PHP SDK

monolog:
  handlers:
    sentry:
      type: sentry
      level: !php/const Monolog\Logger::ERROR
      hub_id: Sentry\State\HubInterface